# Generated by Django 5.2.8 on 2025-12-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_taskdetail_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="detail",
                to="tasks.task",
            ),
        ),
    ]
