# Generated by Django 5.2.8 on 2025-12-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_task_is_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
    ]
