# Generated by Django 5.2.8 on 2025-12-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="assigned_to",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
