# Generated by Django 5.2.8 on 2025-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_remove_project_assigned_to_delete_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="tasks_asset"),
        ),
    ]
